### ISSUE TITLE
Mission editor switch alias labels

### ISSUE THREAD

**Issue by gpsmith1** [wboxx1/85-EIS-PUMA#80]
You can set the switch positions but they don't repopulate in the mission editor correctly. The position you selected does appear in the xml file

Also getting several errors where " " was trying to be cast a an integer.

**Comment by wboxx1** [comment]
I added current cell dirty state changed handlers to all switch grids in the mission editor.  This should improve the user experience by committing and ending an edit to the combobox immediately when an item is selected.  This should reduce/eliminate the amount of errors received due to user clicking out of grid before committing edit.
